language: go
sudo: false

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

install:
  - go get -d -v ./... && go build -v ./...
  - go get gopkg.in/check.v1
  - go get github.com/stretchr/testify
